<definitions name="MDCCalculator"
             targetNamespace="http://localhost:3000/mdc"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://localhost:3000/mdc"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <message name="CalculateMDCRequest">
        <part name="x" type="xsd:int"/>
        <part name="y" type="xsd:int"/>
    </message>
    <message name="CalculateMDCResponse">
        <part name="MDC" type="xsd:int"/>
    </message>

    <portType name="MDCPortType">
        <operation name="CalculateMDC">
            <input message="tns:CalculateMDCRequest"/>
            <output message="tns:CalculateMDCResponse"/>
        </operation>
    </portType>

    <binding name="MDCBinding" type="tns:MDCPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CalculateMDC">
            <soap:operation soapAction="http://localhost:3000/mdc#CalculateMDC"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="MDCService">
        <port name="MDCPort" binding="tns:MDCBinding">
            <soap:address location="http://localhost:3000/mdc"/>
        </port>
    </service>

</definitions>